POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Test Event",
    "description": "Test Event",
    "location": "Test Location",
    "dateTime": "2025-01-01T13:30:00.000Z"
}
